upcv_app/empleados_app/aulapro/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('establecimientos/', views.establecimientos_list, name='establecimientos_list'),
    path('establecimientos/<int:est_id>/', views.establecimiento_detail, name='establecimiento_detail'),

    path('establecimientos/<int:est_id>/ciclos/', views.ciclos_list, name='ciclos_list'),
    path('establecimientos/<int:est_id>/ciclos/nuevo/', views.ciclo_create, name='ciclo_create'),
    path('establecimientos/<int:est_id>/ciclos/<int:ciclo_id>/', views.ciclo_detail, name='ciclo_detail'),
    path('establecimientos/<int:est_id>/ciclos/<int:ciclo_id>/editar/', views.ciclo_update, name='ciclo_update'),
    path('establecimientos/<int:est_id>/ciclos/<int:ciclo_id>/carreras/nuevo/', views.carrera_create, name='carrera_create'),
    path('establecimientos/<int:est_id>/ciclos/<int:ciclo_id>/activar/', views.ciclo_activar, name='ciclo_activar'),
    path('establecimientos/<int:est_id>/ciclos/<int:ciclo_id>/eliminar/', views.ciclo_delete, name='ciclo_delete'),

    path('establecimientos/<int:est_id>/ciclos/<int:ciclo_id>/carreras/<int:car_id>/', views.carrera_detail, name='carrera_detail'),
    path('establecimientos/<int:est_id>/ciclos/<int:ciclo_id>/carreras/<int:car_id>/grados/nuevo/', views.grado_create, name='grado_create'),
    path('establecimientos/<int:est_id>/ciclos/<int:ciclo_id>/carreras/<int:car_id>/grados/<int:grado_id>/', views.grado_detail, name='grado_detail'),

    path('establecimientos/<int:est_id>/ciclos/<int:ciclo_id>/carreras/<int:car_id>/grados/<int:grado_id>/buscar-alumno/', views.buscar_alumno, name='buscar_alumno'),
    path('establecimientos/<int:est_id>/ciclos/<int:ciclo_id>/carreras/<int:car_id>/grados/<int:grado_id>/matricular/', views.matricular_alumno, name='matricular_alumno'),
    path('matriculas/<int:matricula_id>/desmatricular/', views.desmatricular_alumno, name='desmatricular_alumno'),
]

upcv_app/empleados_app/urls.py
from django.urls import include, path

from . import views

app_name = "empleados"

urlpatterns = [

    # Navegación jerárquica AulaPro
    path('', include('empleados_app.aulapro.urls')),
    path("signin/", views.signin, name="signin"),
    path("logout/", views.signout, name="logout"),
    path("dahsboard/", views.dahsboard, name="dahsboard"),
    path("config_general/", views.configuracion_general, name="configuracion_general"),

    path("alumnos/crear/", views.crear_empleado, name="crear_empleado"),
    path("alumnos/lista/", views.lista_empleados, name="empleado_lista"),
    path("alumnos/lista/<int:e_id>/", views.editar_empleado, name="editar_empleado"),
    path("alumnos/credencial/", views.credencial_empleados, name="empleado_credencial"),
    path("alumnos/<int:id>/", views.empleado_detalle, name="empleado_detalle"),

    path("establecimientos/", views.lista_establecimientos, name="establecimiento_lista"),
    path("establecimientos/crear/", views.crear_establecimiento, name="crear_establecimiento"),
    path("establecimientos/<int:pk>/editar/", views.editar_establecimiento, name="editar_establecimiento"),



    path("matricula/", views.matricula_view, name="matricula"),

    path("matriculas/<int:matricula_id>/gafete.jpg", views.gafete_jpg, name="gafete_jpg"),
    path("matriculas/<int:matricula_id>/gafete_descarga.jpg", views.descargar_gafete_jpg, name="descargar_gafete_jpg"),

    path("establecimientos/<int:establecimiento_id>/gafete/editor/", views.editor_gafete, name="editor_gafete"),
    path("establecimientos/<int:establecimiento_id>/gafete/diseno/guardar/", views.guardar_diseno_gafete, name="guardar_diseno_gafete"),
    path("establecimientos/<int:establecimiento_id>/gafete/diseno/reset/", views.resetear_diseno_gafete, name="resetear_diseno_gafete"),

    # Rutas legacy para compatibilidad
    path("crear/", views.crear_empleado, name="legacy_crear"),
    path("lista/", views.lista_empleados, name="legacy_lista"),
    path("lista/<int:e_id>/", views.editar_empleado, name="legacy_editar"),
    path("credencial/", views.credencial_empleados, name="legacy_credencial"),
    path("empleado/<int:id>/", views.empleado_detalle, name="legacy_detalle"),

    path("", views.home, name="home"),
]

upcv_app/upcv_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from empleados_app import views as empleados_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signin/', empleados_views.signin),
    path('logout/', empleados_views.signout),
    path('aulapro/', include('empleados_app.urls')),
    path('aulapro/', include(('empleados_app.urls', 'alumnos'), namespace='alumnos')),
    path('', RedirectView.as_view(url='/aulapro/signin/', permanent=False)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

upcv_app/empleados_app/aulapro/forms.py
from django import forms

from empleados_app.forms import BaseRihoForm
from empleados_app.models import CicloEscolar, Matricula


class MatriculaFiltroForm(forms.Form):
    ciclo_escolar = forms.ModelChoiceField(queryset=CicloEscolar.objects.none(), required=False, empty_label="Ciclo activo")
    estado = forms.ChoiceField(
        required=False,
        choices=(('', 'Todos'), ('activo', 'Activo'), ('inactivo', 'Inactivo')),
    )

    def __init__(self, *args, **kwargs):
        establecimiento = kwargs.pop('establecimiento', None)
        super().__init__(*args, **kwargs)
        if establecimiento:
            self.fields['ciclo_escolar'].queryset = CicloEscolar.objects.filter(establecimiento=establecimiento).order_by('-anio', '-id')
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MatricularPorCodigoForm(BaseRihoForm):
    codigo_personal = forms.CharField(max_length=30)

    class Meta:
        model = Matricula
        fields = ['estado']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['codigo_personal'].widget.attrs['class'] = 'form-control'
        self.fields['codigo_personal'].widget.attrs['placeholder'] = 'Ej. A-1001'

upcv_app/empleados_app/aulapro/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db import IntegrityError, transaction
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_GET, require_POST

from empleados_app.forms import CarreraForm, CicloEscolarForm, GradoForm
from empleados_app.models import Carrera, CicloEscolar, ConfiguracionGeneral, Empleado, Establecimiento, Grado, Matricula

from .forms import MatriculaFiltroForm

ALLOW_MULTI_GRADE_PER_CYCLE = False


def _can_manage(user):
    return user.is_superuser or user.is_staff or user.groups.filter(name="Admin_gafetes").exists()


def _get_establecimiento(est_id):
    return get_object_or_404(Establecimiento, pk=est_id)


def _get_ciclo(est_id, ciclo_id):
    ciclo = get_object_or_404(CicloEscolar.objects.select_related('establecimiento'), pk=ciclo_id)
    if ciclo.establecimiento_id != est_id:
        raise CicloEscolar.DoesNotExist
    return ciclo


def _get_carrera(est_id, ciclo_id, car_id):
    carrera = get_object_or_404(Carrera.objects.select_related('ciclo_escolar', 'ciclo_escolar__establecimiento'), pk=car_id)
    if carrera.ciclo_escolar_id != ciclo_id or carrera.ciclo_escolar.establecimiento_id != est_id:
        raise Carrera.DoesNotExist
    return carrera


def _get_grado(est_id, ciclo_id, car_id, grado_id):
    grado = get_object_or_404(Grado.objects.select_related('carrera', 'carrera__ciclo_escolar', 'carrera__ciclo_escolar__establecimiento'), pk=grado_id)
    if grado.carrera_id != car_id or not grado.carrera or grado.carrera.ciclo_escolar_id != ciclo_id or grado.carrera.ciclo_escolar.establecimiento_id != est_id:
        raise Grado.DoesNotExist
    return grado


@login_required
def establecimientos_list(request):
    establecimientos = Establecimiento.objects.all()
    return render(request, 'aulapro/establecimientos_list.html', {'establecimientos': establecimientos})


@login_required
def establecimiento_detail(request, est_id):
    establecimiento = _get_establecimiento(est_id)
    ciclos = establecimiento.ciclos_escolares.all().order_by('-anio', '-id')
    return render(request, 'aulapro/establecimiento_detail.html', {
        'establecimiento': establecimiento,
        'ciclos': ciclos,
        'ciclo_activo': establecimiento.get_ciclo_activo(),
    })


@login_required
def ciclos_list(request, est_id):
    establecimiento = _get_establecimiento(est_id)
    ciclos = establecimiento.ciclos_escolares.all().order_by('-anio', '-id')
    return render(request, 'aulapro/ciclos_list.html', {
        'establecimiento': establecimiento,
        'ciclos': ciclos,
    })


@login_required
@user_passes_test(_can_manage)
def ciclo_create(request, est_id):
    establecimiento = _get_establecimiento(est_id)
    form = CicloEscolarForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        ciclo = form.save(commit=False)
        ciclo.establecimiento = establecimiento
        ciclo.activo = bool(form.cleaned_data.get('activo'))

        with transaction.atomic():
            if ciclo.activo:
                establecimiento.ciclos_escolares.filter(activo=True).exclude(pk=ciclo.pk).update(activo=False)
            ciclo.save()

        messages.success(request, 'Ciclo escolar creado correctamente.')
        return redirect('empleados:ciclos_list', est_id=establecimiento.id)

    return render(request, 'aulapro/ciclos_form.html', {
        'establecimiento': establecimiento,
        'form': form,
        'titulo': 'Nuevo ciclo escolar',
        'accion': 'Guardar ciclo',
    })


@login_required
@user_passes_test(_can_manage)
def ciclo_update(request, est_id, ciclo_id):
    establecimiento = _get_establecimiento(est_id)
    ciclo = get_object_or_404(CicloEscolar, pk=ciclo_id, establecimiento=establecimiento)
    form = CicloEscolarForm(request.POST or None, instance=ciclo)

    if request.method == 'POST' and form.is_valid():
        ciclo = form.save(commit=False)
        ciclo.establecimiento = establecimiento
        ciclo.activo = bool(form.cleaned_data.get('activo'))

        with transaction.atomic():
            if ciclo.activo:
                establecimiento.ciclos_escolares.filter(activo=True).exclude(pk=ciclo.pk).update(activo=False)
            ciclo.save()

        messages.success(request, 'Ciclo escolar actualizado correctamente.')
        return redirect('empleados:ciclos_list', est_id=establecimiento.id)

    return render(request, 'aulapro/ciclos_form.html', {
        'establecimiento': establecimiento,
        'form': form,
        'ciclo': ciclo,
        'titulo': 'Editar ciclo escolar',
        'accion': 'Guardar cambios',
    })


@login_required
@user_passes_test(_can_manage)
@require_POST
def ciclo_activar(request, est_id, ciclo_id):
    establecimiento = _get_establecimiento(est_id)
    ciclo = get_object_or_404(CicloEscolar, pk=ciclo_id, establecimiento=establecimiento)
    try:
        with transaction.atomic():
            establecimiento.ciclos_escolares.update(activo=False)
            ciclo.activo = True
            ciclo.save(update_fields=['activo'])
    except IntegrityError:
        messages.error(request, 'No se pudo activar el ciclo por un conflicto de integridad. Intente nuevamente.')
        return redirect('empleados:ciclos_list', est_id=establecimiento.id)

    messages.success(request, f'El ciclo {ciclo.nombre} ahora está activo.')
    return redirect(request.POST.get('next') or 'empleados:ciclos_list', est_id=establecimiento.id)


@login_required
@user_passes_test(_can_manage)
@require_POST
def ciclo_delete(request, est_id, ciclo_id):
    establecimiento = _get_establecimiento(est_id)
    ciclo = get_object_or_404(CicloEscolar, pk=ciclo_id, establecimiento=establecimiento)

    if ciclo.matriculas.exists():
        messages.warning(request, 'No se puede eliminar el ciclo porque tiene matrículas asociadas.')
        return redirect('empleados:ciclos_list', est_id=establecimiento.id)

    if ciclo.activo:
        messages.warning(request, 'No se puede eliminar el ciclo activo. Active otro ciclo primero.')
        return redirect('empleados:ciclos_list', est_id=establecimiento.id)

    ciclo.delete()
    messages.success(request, 'Ciclo escolar eliminado correctamente.')
    return redirect('empleados:ciclos_list', est_id=establecimiento.id)



@login_required
def ciclo_detail(request, est_id, ciclo_id):
    establecimiento = _get_establecimiento(est_id)
    ciclo = _get_ciclo(est_id, ciclo_id)
    carreras = ciclo.carreras.all().order_by('nombre')
    form = CarreraForm(initial={'ciclo_escolar': ciclo, 'activo': True})
    return render(request, 'aulapro/ciclo_detail.html', {
        'establecimiento': establecimiento,
        'ciclo': ciclo,
        'carreras': carreras,
        'form_carrera': form,
    })




@login_required
@user_passes_test(_can_manage)
def carrera_create(request, est_id, ciclo_id):
    ciclo = _get_ciclo(est_id, ciclo_id)
    form = CarreraForm(request.POST or None, initial={'ciclo_escolar': ciclo, 'activo': True})
    if request.method == 'POST' and form.is_valid():
        carrera = form.save(commit=False)
        carrera.ciclo_escolar = ciclo
        carrera.save()
        messages.success(request, 'Carrera creada correctamente.')
        return redirect('empleados:ciclo_detail', est_id=est_id, ciclo_id=ciclo_id)

    return render(request, 'empleados/carrera_form.html', {
        'form': form,
        'titulo': f'Nueva carrera - {ciclo.nombre}',
    })

@login_required
def carrera_detail(request, est_id, ciclo_id, car_id):
    establecimiento = _get_establecimiento(est_id)
    ciclo = _get_ciclo(est_id, ciclo_id)
    carrera = _get_carrera(est_id, ciclo_id, car_id)
    grados = Grado.objects.filter(carrera=carrera).order_by('nombre')
    return render(request, 'aulapro/carrera_detail.html', {
        'establecimiento': establecimiento,
        'ciclo': ciclo,
        'carrera': carrera,
        'grados': grados,
    })


@login_required
@user_passes_test(_can_manage)
def grado_create(request, est_id, ciclo_id, car_id):
    ciclo = _get_ciclo(est_id, ciclo_id)
    carrera = _get_carrera(est_id, ciclo_id, car_id)
    form = GradoForm(request.POST or None, initial={'carrera': carrera, 'activo': True})
    if request.method == 'POST' and form.is_valid():
        grado = form.save(commit=False)
        grado.carrera = carrera
        grado.save()
        messages.success(request, 'Grado creado correctamente.')
        return redirect('empleados:carrera_detail', est_id=est_id, ciclo_id=ciclo_id, car_id=car_id)

    return render(request, 'empleados/grado_form.html', {
        'form': form,
        'titulo': f'Nuevo grado - {carrera.nombre}',
        'ciclo': ciclo,
        'carrera': carrera,
    })



@login_required
def grado_detail(request, est_id, ciclo_id, car_id, grado_id):
    establecimiento = _get_establecimiento(est_id)
    ciclo = _get_ciclo(est_id, ciclo_id)
    carrera = _get_carrera(est_id, ciclo_id, car_id)
    grado = _get_grado(est_id, ciclo_id, car_id, grado_id)

    ciclo_activo = establecimiento.get_ciclo_activo()
    filtro_form = MatriculaFiltroForm(request.GET or None, establecimiento=establecimiento)
    matriculas = Matricula.objects.select_related('alumno', 'ciclo_escolar').filter(grado=grado)

    ciclo_filtrado = None
    if filtro_form.is_valid():
        estado = filtro_form.cleaned_data.get('estado')
        ciclo_filtrado = filtro_form.cleaned_data.get('ciclo_escolar')
        if estado:
            matriculas = matriculas.filter(estado=estado)

    if ciclo_filtrado:
        matriculas = matriculas.filter(ciclo_escolar=ciclo_filtrado)
    elif ciclo_activo:
        matriculas = matriculas.filter(ciclo_escolar=ciclo_activo)

    configuracion = ConfiguracionGeneral.objects.first()
    layout = establecimiento.get_layout()

upcv_app/empleados_app/templates/aulapro/carrera_detail.html
{% extends 'empleados/base.html' %}
{% block content %}
<div class="page-body"><div class="container-fluid"><div class="page-title"><div class="row"><div class="col-6"><h4>{{ carrera.nombre }}</h4></div><div class="col-6"><ol class="breadcrumb"><li class="breadcrumb-item">AulaPro</li><li class="breadcrumb-item"><a href="{% url 'empleados:establecimientos_list' %}">Establecimientos</a></li><li class="breadcrumb-item"><a href="{% url 'empleados:establecimiento_detail' establecimiento.id %}">{{ establecimiento.nombre }}</a></li><li class="breadcrumb-item"><a href="{% url 'empleados:ciclo_detail' establecimiento.id ciclo.id %}">{{ ciclo.nombre }}</a></li><li class="breadcrumb-item active">{{ carrera.nombre }}</li></ol></div></div></div></div>
<div class="container-fluid"><div class="card"><div class="card-header card-no-border pb-0 d-flex justify-content-between align-items-center"><h5>Detalle de carrera</h5><a class="btn btn-primary btn-sm" href="{% url 'empleados:grado_create' establecimiento.id ciclo.id carrera.id %}">Nuevo grado</a></div><div class="card-body"><p class="mb-0 text-muted">Grados disponibles para {{ carrera.nombre }}.</p></div></div>
<div class="card"><div class="card-header card-no-border pb-0"><h5>Grados</h5></div><div class="card-body table-responsive"><table class="table table-striped"><thead><tr><th>Nombre</th><th>Jornada</th><th>Sección</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{% for g in grados %}<tr><td>{{ g.nombre }}</td><td>{{ g.jornada|default:'-' }}</td><td>{{ g.seccion|default:'-' }}</td><td>{% if g.activo %}<span class="badge badge-light-success">Activo</span>{% else %}<span class="badge badge-light-danger">Inactivo</span>{% endif %}</td><td><a class="btn btn-primary btn-sm" href="{% url 'empleados:grado_detail' establecimiento.id ciclo.id carrera.id g.id %}">Entrar</a></td></tr>{% empty %}<tr><td colspan="5">Sin grados.</td></tr>{% endfor %}</tbody></table></div></div>
</div></div>
{% endblock %}

upcv_app/empleados_app/templates/aulapro/ciclo_detail.html
{% extends 'empleados/base.html' %}
{% block content %}
<div class="page-body"><div class="container-fluid"><div class="page-title"><div class="row"><div class="col-6"><h4>{{ ciclo.nombre }}</h4></div><div class="col-6"><ol class="breadcrumb"><li class="breadcrumb-item">AulaPro</li><li class="breadcrumb-item"><a href="{% url 'empleados:establecimientos_list' %}">Establecimientos</a></li><li class="breadcrumb-item"><a href="{% url 'empleados:establecimiento_detail' establecimiento.id %}">{{ establecimiento.nombre }}</a></li><li class="breadcrumb-item active">{{ ciclo.nombre }}</li></ol></div></div></div></div>
<div class="container-fluid">
  <div class="card"><div class="card-header card-no-border pb-0 d-flex justify-content-between align-items-center"><h5>{{ ciclo.nombre }}</h5><div class="d-flex gap-2">{% if ciclo.activo %}<span class="badge badge-light-success">Activo</span>{% else %}<span class="badge badge-light-secondary">Inactivo</span>{% endif %}<a class="btn btn-primary btn-sm" href="{% url 'empleados:carrera_create' establecimiento.id ciclo.id %}">Nueva carrera</a></div></div><div class="card-body"><p class="mb-0 text-muted">Año: {{ ciclo.anio|default:'-' }} · Fechas: {{ ciclo.fecha_inicio|default:'-' }} al {{ ciclo.fecha_fin|default:'-' }}</p></div></div>

  <div class="card"><div class="card-header card-no-border pb-0"><h5>Carreras del ciclo</h5></div><div class="card-body table-responsive"><table class="table table-striped"><thead><tr><th>Nombre</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{% for c in carreras %}<tr><td>{{ c.nombre }}</td><td>{% if c.activo %}<span class="badge badge-light-success">Activa</span>{% else %}<span class="badge badge-light-danger">Inactiva</span>{% endif %}</td><td><a class="btn btn-primary btn-sm" href="{% url 'empleados:carrera_detail' establecimiento.id ciclo.id c.id %}">Entrar</a></td></tr>{% empty %}<tr><td colspan="3">Sin carreras para este ciclo.</td></tr>{% endfor %}</tbody></table></div></div>
</div></div>
{% endblock %}

upcv_app/empleados_app/templates/aulapro/ciclos_list.html
{% extends 'empleados/base.html' %}
{% block content %}
<div class="page-body">
  <div class="container-fluid">
    <div class="page-title"><div class="row"><div class="col-6"><h4>Ciclos escolares</h4></div><div class="col-6"><ol class="breadcrumb"><li class="breadcrumb-item">AulaPro</li><li class="breadcrumb-item"><a href="{% url 'empleados:establecimientos_list' %}">Establecimientos</a></li><li class="breadcrumb-item"><a href="{% url 'empleados:establecimiento_detail' establecimiento.id %}">{{ establecimiento.nombre }}</a></li><li class="breadcrumb-item active">Ciclos escolares</li></ol></div></div></div>
  </div>
  <div class="container-fluid">
    <div class="card"><div class="card-header card-no-border pb-0 d-flex justify-content-between align-items-center"><h5>Listado de ciclos</h5><a class="btn btn-primary btn-sm" href="{% url 'empleados:ciclo_create' establecimiento.id %}"><i class="fa fa-plus"></i> Nuevo ciclo</a></div><div class="card-body table-responsive"><table class="table table-striped"><thead><tr><th>Nombre</th><th>Año</th><th>Activo</th><th>Acciones</th></tr></thead><tbody>{% for c in ciclos %}<tr><td>{{ c.nombre }}</td><td>{{ c.anio|default:'-' }}</td><td>{% if c.activo %}<span class="badge badge-light-success">Activo</span>{% else %}<span class="badge badge-light-secondary">Inactivo</span>{% endif %}</td><td><div class="d-flex gap-2 flex-wrap"><a class="btn btn-primary btn-sm" href="{% url 'empleados:ciclo_detail' establecimiento.id c.id %}">Entrar</a><a class="btn btn-outline-info btn-sm" href="{% url 'empleados:ciclo_update' establecimiento.id c.id %}">Editar</a>{% if not c.activo %}<form method="post" action="{% url 'empleados:ciclo_activar' establecimiento.id c.id %}">{% csrf_token %}<input type="hidden" name="next" value="{{ request.get_full_path }}"><button class="btn btn-outline-primary btn-sm" type="submit">Activar</button></form>{% endif %}<form method="post" action="{% url 'empleados:ciclo_delete' establecimiento.id c.id %}" onsubmit="return confirm('¿Desea eliminar este ciclo escolar?');">{% csrf_token %}<button class="btn btn-outline-danger btn-sm" type="submit">Eliminar</button></form></div></td></tr>{% empty %}<tr><td colspan="4">No hay ciclos registrados.</td></tr>{% endfor %}</tbody></table></div></div>
  </div>
</div>
{% endblock %}

upcv_app/empleados_app/templates/aulapro/establecimiento_detail.html
{% extends 'empleados/base.html' %}
{% block content %}
<div class="page-body"><div class="container-fluid"><div class="page-title"><div class="row"><div class="col-6"><h4>{{ establecimiento.nombre }}</h4></div><div class="col-6"><ol class="breadcrumb"><li class="breadcrumb-item">AulaPro</li><li class="breadcrumb-item"><a href="{% url 'empleados:establecimientos_list' %}">Establecimientos</a></li><li class="breadcrumb-item active">{{ establecimiento.nombre }}</li></ol></div></div></div></div>
<div class="container-fluid">
  <div class="card"><div class="card-header card-no-border pb-0 d-flex justify-content-between"><h5>Detalle del establecimiento</h5><div class="d-flex gap-2"><a class="btn btn-outline-primary btn-sm" href="{% url 'empleados:editar_establecimiento' establecimiento.id %}">Editar</a><a class="btn btn-outline-info btn-sm" href="{% url 'empleados:editor_gafete' establecimiento.id %}">Diseño de Gafete</a></div></div><div class="card-body"><p class="mb-1"><strong>Dirección:</strong> {{ establecimiento.direccion|default:'-' }}</p>{% if ciclo_activo %}<p class="mb-0"><strong>Ciclo activo:</strong> <span class="badge badge-light-success">{{ ciclo_activo.nombre }}</span></p>{% else %}<p class="mb-0"><strong>Ciclo activo:</strong> <span class="badge badge-light-danger">Sin ciclo activo</span></p>{% endif %}</div></div>

  <div class="card"><div class="card-header card-no-border pb-0 d-flex justify-content-between align-items-center"><h5>Ciclos escolares</h5><div class="d-flex gap-2"><a class="btn btn-primary btn-sm" href="{% url 'empleados:ciclo_create' establecimiento.id %}"><i class="fa fa-plus"></i> Nuevo ciclo</a><a class="btn btn-outline-primary btn-sm" href="{% url 'empleados:ciclos_list' establecimiento.id %}">Ver todos</a></div></div><div class="card-body table-responsive"><table class="table table-striped"><thead><tr><th>Nombre</th><th>Año</th><th>Fechas</th><th>Activo</th><th>Acciones</th></tr></thead><tbody>{% for c in ciclos %}<tr><td>{{ c.nombre }}</td><td>{{ c.anio|default:'-' }}</td><td>{% if c.fecha_inicio or c.fecha_fin %}{{ c.fecha_inicio|default:'-' }} al {{ c.fecha_fin|default:'-' }}{% else %}-{% endif %}</td><td>{% if c.activo %}<span class="badge badge-light-success">Activo</span>{% else %}<span class="badge badge-light-secondary">Inactivo</span>{% endif %}</td><td><div class="d-flex gap-2">{% if not c.activo %}<form method="post" action="{% url 'empleados:ciclo_activar' establecimiento.id c.id %}">{% csrf_token %}<input type="hidden" name="next" value="{{ request.get_full_path }}"><button class="btn btn-outline-primary btn-sm" type="submit">Activar</button></form>{% else %}<span class="text-success small align-self-center">Ciclo activo</span>{% endif %}<a class="btn btn-primary btn-sm" href="{% url 'empleados:ciclo_detail' establecimiento.id c.id %}">Ver carreras</a></div></td></tr>{% empty %}<tr><td colspan="5">Sin ciclos escolares.</td></tr>{% endfor %}</tbody></table></div></div>
</div></div>
{% endblock %}